apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-files-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-csi
  csi:
    driver: file.csi.azure.com
    volumeHandle: app-files-pv
    volumeAttributes:
      shareName: app-files
    nodeStageSecretRef:
      name: azure-files-secret
      namespace: arabicmusicencyclopedia