apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-files-pvc
  namespace: arabicmusicencyclopedia
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: app-files-pv
  resources:
    requests:
      storage: 1Gi