apiVersion: v1
kind: Secret
metadata:
  name: azure-files-secret
  namespace: arabicmusicencyclopedia
type: Opaque
stringData:
  azurestorageaccountname: sbxstaksdemo
  azurestorageaccountkey: <storage-account-key>