name: Deploy ACKungFuDoc app

on:
  push: #TODO REMOVE THIS!!!!
    branches:
      - main
      - dev
  workflow_run:
    workflows: ["Deploy infrastructure"]
    types:
      - completed
    branches:
      - main
      - dev

jobs:
  deploy:
    #TODO: add this again if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      id-token: write

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout ACKungFuDoc repo
        uses: actions/checkout@v4
        with:
            repository: aczwink/KungFuWiki
            path: ackungfudoc

      - name: Build ACKungFuDoc #TODO: should use ci here
        run: |
          npm i
          npm run build
        working-directory: ./ackungfudoc

      #TODO: do a webpack bundle!
      - name: Build node webserver
        run: cp ./integration/node-webserver/package.json ./ackungfudoc/dist/out/
      - name: Build node webserver 2
        run: npm i
        working-directory: ./ackungfudoc/dist/out/

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
      - name: Deploying to App Service
        run: |
          zip -r ./azure.zip .
          az webapp deploy --resource-group prd-rg-kungfudoc --name ackungfudoc --src-path ./azure.zip
        working-directory: ./ackungfudoc/dist/out